name: 'egypt_air_quality'
version: '1.0.0'
config-version: 2

profile: 'snowflake'

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

models:
  egypt_air_quality:
    staging:
      +materialized: view
      +schema: staging

    marts:
      +schema: marts

      facts:
        +materialized: table

      dimensions:
        +materialized: table
flags:
  require_generic_test_arguments_property: true