name: "air_quality_egypt"
version: "1.0.0"
config-version: 2

profile: "default"   # ← لو اسم الـ profile مختلف ابعتيلي أعدله

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
test-paths: ["tests"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  air_quality_egypt:
    staging:
      +materialized: view
    intermediate:
      +materialized: table
    marts:
      +materialized: table
