version: 2

sources:
  - name: air_quality_source             
    database: AIR_QUALITY_DB             
    schema: EGYPT_DATA                    
    tables:
      - name: AIR_QUALITY_NASA
        description: "Raw air quality data from NASA sources."
      - name: AIR_QUALITY         
        description: "Recent air quality data collected from OpenAQ or other sensors."
